
name: labeled2

on:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - name: hellohello
        run: echo HelloHello
      - uses: actions/checkout@v3
      - name: echo dummy
        run:  echo dummy.txt
